### ISSUE TITLE
contents/songs_rape.tex not compiling

### ISSUE THREAD

**Issue by antagomir** [unilaiva/unilaiva-songbook#2]
I added a file contents/songs_rape.tex and also added it in ./unilaiva-songbook.tex (now commented out). This does not compile the PDF successfully. I tried to check the manual but didn't manage to debug so far. Any quick tips would be appreciated.

**Comment by unilarva** [comment]
Well..

With a glance I notice that you are trying to mark the song with a tag named `rape`, but there is no tag with that name. Instead there is a tag called `rapé`. That will cause compilation to fail. All tags must be listed in the file `tags.can`; see it for the list of existing tags and add new ones as needed.

May I ask the idea behind putting that one song in its own file and creating a specific chapter only for it? Before this we had 6 chapters for different languages plus the chapter for "technical information". Since your song is in Portuguese, would you consider adding it to the `songs_portuguese.tex` instead? Perhaps next to the other song in that chapter with a tag `rapé`.

Also, you are giving your new chapter song numbers starting from 200. Those numbers are already in use by the English chapter. I don't know if this causes an error in compilation, but it is perhaps a bit strange to have more than one song with the same number.

If you add a song with missing chords, please consider adding the tag `(chords missing)` (with parenthesis) so that it can be easily found later for inserting the chords.

If it is not too much trouble, one could also see the existing files for indentation style and such. Also earlier commit messages might be worth a look. (For example, if every new song is added with a commit message "Add 'songname'" they can be easily found from the commit log.)

I think it would be good practice to *only push to the main repo, when the source compiles*!

Sorry for all the critique, you can mostly take it as a set of suggestions. Thanks for your contribution!

**Comment by unilarva** [comment]
Would you like me to fix it (as per my suggestions) for you? It would be nice to get the main repository to compile asap.

**Comment by antagomir** [comment]
Excellent. Looking at it now. 

The source does compiles, though. I did not push broken code.

**Comment by antagomir** [comment]
Fixed. The explanations sped up the process considerably.

Had played around with the tag but had missed tags.can. The plan was to fix song numbers after being able to compile but indeed that may have been part of the issue.  

Motivation for new chapter was that there is at least one more song to add, this would make 3 rapé songs altogether. But can go to Portuguese chapter now.

Going to look at the style. In this song the complete verse is repeated, and within that the second part (line) is repeated twice. I will have to find an example on how to mark this.

**Comment by antagomir** [comment]
Done.

**Comment by unilarva** [comment]
Thanks. (And yes, all your pushed code did actually compile, as you said.)

As per your idea, I've now put the rapé songs (now four) in their own section, but within the Portuguese chapter (and file). Is this solution ok for you? See commit 32ca6b0f.

**Comment by antagomir** [comment]
Yee its great \o/
